// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnC6dnQ9yA5HlLIyl-F9eRd42jMClVMAY',
    appId: '1:395877805112:web:f241e793697fca1611cacd',
    messagingSenderId: '395877805112',
    projectId: 'wechat-c8d72',
    authDomain: 'wechat-c8d72.firebaseapp.com',
    storageBucket: 'wechat-c8d72.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJWPRLWTfWc3raLbiItc2rEmbTCDs0uxk',
    appId: '1:395877805112:android:112e48f81f4a467511cacd',
    messagingSenderId: '395877805112',
    projectId: 'wechat-c8d72',
    storageBucket: 'wechat-c8d72.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBSEilC6501wPCSaO5yhkQbwXalo3T1qQ',
    appId: '1:395877805112:ios:a73bb56f014f23bf11cacd',
    messagingSenderId: '395877805112',
    projectId: 'wechat-c8d72',
    storageBucket: 'wechat-c8d72.appspot.com',
    androidClientId: '395877805112-fjqskuugk7em68gmfm053n9f2m7i64vp.apps.googleusercontent.com',
    iosClientId: '395877805112-c37nfvf0qicq4h6c0jkeek817matg4bj.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBSEilC6501wPCSaO5yhkQbwXalo3T1qQ',
    appId: '1:395877805112:ios:7d5deffe3e4e2d4411cacd',
    messagingSenderId: '395877805112',
    projectId: 'wechat-c8d72',
    storageBucket: 'wechat-c8d72.appspot.com',
    androidClientId: '395877805112-fjqskuugk7em68gmfm053n9f2m7i64vp.apps.googleusercontent.com',
    iosClientId: '395877805112-up3bgsttbu2ii2dt75urqia6h16a278q.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
